
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 18 23:12:43 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 31;
  public static final int EQUALITY = 24;
  public static final int INCREMENT = 43;
  public static final int GREATER_OR_EQUAL = 30;
  public static final int CONST = 14;
  public static final int CONTINUE = 38;
  public static final int LPAREN = 6;
  public static final int GREATER = 29;
  public static final int SEMI = 5;
  public static final int LEFT_SQUARE_BRAC = 19;
  public static final int DECREMENT = 44;
  public static final int MINUS = 41;
  public static final int LESS = 26;
  public static final int FOR = 22;
  public static final int RPAREN = 7;
  public static final int LESS_OR_EQUAL = 28;
  public static final int COMMA = 11;
  public static final int CLASS = 15;
  public static final int MULTIPLYEQUAL = 49;
  public static final int MULTIPLY = 42;
  public static final int PLUS = 10;
  public static final int QUOTE = 27;
  public static final int IF = 34;
  public static final int DOT = 47;
  public static final int ABSTRACT = 37;
  public static final int EOF = 0;
  public static final int DIVIDEEQUAL = 50;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int LOGICAL_OR = 21;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int PLUSEQUAL = 52;
  public static final int NUMBER = 16;
  public static final int MOD = 32;
  public static final int BREAK = 39;
  public static final int IDENT = 33;
  public static final int VOID = 13;
  public static final int RIGHT_SQUARE_BRAC = 20;
  public static final int COLON = 48;
  public static final int FOREACH = 46;
  public static final int ELSE = 35;
  public static final int LBRACE = 3;
  public static final int READ = 23;
  public static final int DIFFERENCE = 25;
  public static final int MINUSEQUAL = 53;
  public static final int CHARCONST = 18;
  public static final int LOGICAL_AND = 40;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 36;
  public static final int BOOLCONST = 17;
  public static final int PROG = 2;
  public static final int MODEQUAL = 51;
  public static final int PRINT = 12;
}

